Added LINENOs and removed /bin/date

diff --git a/bdl b/bdl
--- a/bdl
+++ b/bdl
@@ -3,21 +3,16 @@
 #----------------------------------------------------------------------------------
 # Project Name      - bdl
 # Started On        - Sat 16 Sep 22:34:12 BST 2017
-# Last Change       - Tue  3 Oct 23:33:56 BST 2017
+# Last Change       - Wed  4 Oct 21:30:40 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
 
-XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
-ERR(){ echo "ERROR: $1" 1>&2; }
+XERR(){ echo "[L${LINENO}] ERROR: $1" 1>&2; exit 1; }
+ERR(){ echo "[L${LINENO}] ERROR: $1" 1>&2; }
 
 DEPCOUNT=0
-for DEP in\
-\
-	/usr/bin/{wc,find,wget,head}\
-	/bin/{sync,mkdir,uname,date}\
-	/sbin/shutdown
-{
+for DEP in /usr/bin/{wc,find,wget,head} /bin/{sync,mkdir,uname} /sbin/shutdown; {
 	[ -x "$DEP" ] || {
 		ERR "Dependency '$DEP' not met."
 		let DEPCOUNT++
@@ -43,7 +38,7 @@ USAGE(){
 	while read -r; do
 		echo "$REPLY"
 	done <<-EOF
-		            BDL - Batch Downloader (3rd October 2017)
+		            BDL - Batch Downloader (4th October 2017)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 		
 		            Easily and quickly download a batch of files using wget.
@@ -82,7 +77,7 @@ INIT_MAIN(){
 			VFLAG="-v" ;;
 	esac
 
-	echo -e "[ `/bin/date +%F\ %X` ] Lines detected in bdl"\
+	echo -e "[ `printf '%(%F %X)T\n'` ] Lines detected in bdl"\
 		"list: $(/usr/bin/wc -l < "$BDL_FILE")\n"
 
 	for LINK in `< "$BDL_FILE"`; {
